/*
DROP TABLE if EXISTS donations;
CREATE TABLE IF NOT EXISTS donations(customer_email VARCHAR(100) PRIMARY KEY,reference VARCHAR(50),customer_name VARCHAR(100), amount_in_cents INT, currency VARCHAR(10), date TIMESTAMP,status VARCHAR(20), clientid INT);
DROP TABLE if EXISTS DONACION;
CREATE TABLE IF NOT EXISTS DONACION (ID INTEGER PRIMARY KEY AUTOINCREMENT,AMOUNT_IN_CENTS INT,CURRENCY VARCHAR(100),DATE TIMESTAMP,STATUS VARCHAR(10),CLIENTID INT,FOREIGN KEY (CLIENTID) REFERENCES CLIENTE(ID));
DROP TABLE if EXISTS CLIENTE;
CREATE TABLE IF NOT EXISTS CLIENTE(ID INTEGER PRIMARY KEY AUTOINCREMENT,NOMBRE VARCHAR(250),NUMERODOC VARCHAR(100) UNIQUE,TIPODOC VARCHAR(100),CORREO VARCHAR(250));
*/
DROP TABLE IF EXISTS DETALL_FACTURA;
DROP TABLE IF EXISTS FACTURA;
DROP TABLE IF EXISTS PRODUCTO;
DROP TABLE IF EXISTS ARTICULO;
DROP TABLE IF EXISTS PARAMETRO;

CREATE TABLE IF NOT EXISTS PARAMETRO (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  NOMBRE VARCHAR(100),
  DESCRIPCION VARCHAR(100),
  VALOR VARCHAR(100),
  AGRUPADOR VARCHAR(100),
  ESTADO INT
);

CREATE TABLE IF NOT EXISTS ARTICULO (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  NOMBRE VARCHAR(100),
  CODIGO VARCHAR(100),
  DESCRIPCION VARCHAR(100),  
  FIGURE_CLASS VARCHAR(250),
  IMG_SRC VARCHAR(250),
  IMG_ALT VARCHAR(250),
  IMG_CLASS VARCHAR(250),
  IMG_ON_CLICK VARCHAR(250),
  DATA_CODIGO VARCHAR(250),
  DATA_NOMBRE VARCHAR(250),
  DATA_DESCRIPCION VARCHAR(250),
  FIGCAPTION VARCHAR(250),
  ESTADO INT  
);

CREATE TABLE IF NOT EXISTS PRODUCTO (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  ID_ARTICULO INT,
  ID_PARAMETRO INT,
  DATA_PRECIO INT,
  ESTADO INT,
  FOREIGN KEY (ID_ARTICULO) REFERENCES ARTICULO(ID),
  FOREIGN KEY (ID_PARAMETRO) REFERENCES PARAMETRO(ID)
);

CREATE TABLE IF NOT EXISTS FACTURA (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  CODIGO VARCHAR(200) UNIQUE,
  ID_CLIENTE INT,  
  VALOR_FACT INT,
  MONEDA VARCHAR(100),
  FECHA_VENTA TIMESTAMP,
  ESTADO VARCHAR(10),  
  PAGADO INT,
  ARTICULO_ENVIADO VARCHAR(100),
  FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID)
);

CREATE TABLE IF NOT EXISTS DETALL_FACTURA (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  ID_FACTURA INT,
  ID_PRODUCTO INT,
  CANTIDAD INT,
  VALOR_UNITARIO INT,
  VALOR_TOTAL INT,  
  FOREIGN KEY (ID_FACTURA) REFERENCES FACTURA(ID),
  FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO(ID)
);

INSERT INTO ARTICULO (NOMBRE, CODIGO, DESCRIPCION, FIGURE_CLASS, IMG_SRC, IMG_ALT, IMG_CLASS, IMG_ON_CLICK, DATA_CODIGO, DATA_NOMBRE, DATA_DESCRIPCION, FIGCAPTION, ESTADO) VALUES ('Camisa tipo polo PFep', 'POL001', 'Camisa 100% algodón con logo PFep', 'wp-block-image size-large', 'https://www.peerkals.com/wp/wp-content/uploads/2025/08/camisas_6-683x1024.png', 'Camisa tipo polo PFep', 'wp-image-263 camisa-preview', 'handleClick(this)', 'POL001', 'Camisa tipo polo PFep', 'Camisa 100% algodón con logo PFep', 'Camisa tipo polo PFep', 1);
INSERT INTO PARAMETRO (NOMBRE, DESCRIPCION, VALOR, AGRUPADOR, ESTADO) VALUES ('Talla', 'Talla de la prenda', 'S', 'TALLA', 1);
INSERT INTO PRODUCTO (ID_ARTICULO, ID_PARAMETRO, DATA_PRECIO, ESTADO) VALUES (1, 1, 49900, 1);
INSERT INTO PARAMETRO (NOMBRE, DESCRIPCION, VALOR, AGRUPADOR, ESTADO) VALUES ('Talla', 'Talla de la prenda', 'M', 'TALLA', 1);
INSERT INTO PRODUCTO (ID_ARTICULO, ID_PARAMETRO, DATA_PRECIO, ESTADO) VALUES (1, 2, 49900, 1);
INSERT INTO PARAMETRO (NOMBRE, DESCRIPCION, VALOR, AGRUPADOR, ESTADO) VALUES ('Talla', 'Talla de la prenda', 'L', 'TALLA', 1);
INSERT INTO PRODUCTO (ID_ARTICULO, ID_PARAMETRO, DATA_PRECIO, ESTADO) VALUES (1, 3, 49900, 1);
INSERT INTO PARAMETRO (NOMBRE, DESCRIPCION, VALOR, AGRUPADOR, ESTADO) VALUES ('Talla', 'Talla de la prenda', 'XL', 'TALLA', 1);
INSERT INTO PRODUCTO (ID_ARTICULO, ID_PARAMETRO, DATA_PRECIO, ESTADO) VALUES (1, 4, 49900, 1);
INSERT INTO ARTICULO (NOMBRE, CODIGO, DESCRIPCION, FIGURE_CLASS, IMG_SRC, IMG_ALT, IMG_CLASS, IMG_ON_CLICK, DATA_CODIGO, DATA_NOMBRE, DATA_DESCRIPCION, FIGCAPTION, ESTADO) VALUES ('Camisa tipo polo blanca PFep', 'POL002', 'Camisa blanca con logo PFep bordado', 'wp-block-image size-large', 'https://www.peerkals.com/wp/wp-content/uploads/2025/08/camisas_4-683x1024.png', 'Camisa tipo polo blanca PFep', 'wp-image-261 camisa-preview', 'handleClick(this)', 'POL002', 'Camisa tipo polo blanca PFep', 'Camisa blanca con logo PFep bordado', 'Camisa tipo polo blanca PFep', 1);
INSERT INTO PARAMETRO (NOMBRE, DESCRIPCION, VALOR, AGRUPADOR, ESTADO) VALUES ('Talla', 'Talla de la prenda', 'S', 'TALLA', 1);
INSERT INTO PRODUCTO (ID_ARTICULO, ID_PARAMETRO, DATA_PRECIO, ESTADO) VALUES (2, 5, 49900, 1);
INSERT INTO PARAMETRO (NOMBRE, DESCRIPCION, VALOR, AGRUPADOR, ESTADO) VALUES ('Talla', 'Talla de la prenda', 'M', 'TALLA', 1);
INSERT INTO PRODUCTO (ID_ARTICULO, ID_PARAMETRO, DATA_PRECIO, ESTADO) VALUES (2, 6, 49900, 1);
INSERT INTO PARAMETRO (NOMBRE, DESCRIPCION, VALOR, AGRUPADOR, ESTADO) VALUES ('Talla', 'Talla de la prenda', 'L', 'TALLA', 1);
INSERT INTO PRODUCTO (ID_ARTICULO, ID_PARAMETRO, DATA_PRECIO, ESTADO) VALUES (2, 7, 49900, 1);
INSERT INTO PARAMETRO (NOMBRE, DESCRIPCION, VALOR, AGRUPADOR, ESTADO) VALUES ('Talla', 'Talla de la prenda', 'XL', 'TALLA', 1);
INSERT INTO PRODUCTO (ID_ARTICULO, ID_PARAMETRO, DATA_PRECIO, ESTADO) VALUES (2, 8, 49900, 1);
INSERT INTO ARTICULO (NOMBRE, CODIGO, DESCRIPCION, FIGURE_CLASS, IMG_SRC, IMG_ALT, IMG_CLASS, IMG_ON_CLICK, DATA_CODIGO, DATA_NOMBRE, DATA_DESCRIPCION, FIGCAPTION, ESTADO) VALUES ('Camisa tipo polo azul PFep', 'POL003', 'Camisa azul con logo PFep en el pecho', 'wp-block-image size-large', 'https://www.peerkals.com/wp/wp-content/uploads/2025/08/camisas_1-1024x683.png', 'Camisa tipo polo azul PFep', 'wp-image-258 camisa-preview', 'handleClick(this)', 'POL003', 'Camisa tipo polo azul PFep', 'Camisa azul con logo PFep en el pecho', 'Camisa tipo polo azul PFep', 1);
INSERT INTO PARAMETRO (NOMBRE, DESCRIPCION, VALOR, AGRUPADOR, ESTADO) VALUES ('Talla', 'Talla de la prenda', 'S', 'TALLA', 1);
INSERT INTO PRODUCTO (ID_ARTICULO, ID_PARAMETRO, DATA_PRECIO, ESTADO) VALUES (3, 9, 49900, 1);
INSERT INTO PARAMETRO (NOMBRE, DESCRIPCION, VALOR, AGRUPADOR, ESTADO) VALUES ('Talla', 'Talla de la prenda', 'M', 'TALLA', 1);
INSERT INTO PRODUCTO (ID_ARTICULO, ID_PARAMETRO, DATA_PRECIO, ESTADO) VALUES (3, 10, 49900, 1);
INSERT INTO PARAMETRO (NOMBRE, DESCRIPCION, VALOR, AGRUPADOR, ESTADO) VALUES ('Talla', 'Talla de la prenda', 'L', 'TALLA', 1);
INSERT INTO PRODUCTO (ID_ARTICULO, ID_PARAMETRO, DATA_PRECIO, ESTADO) VALUES (3, 11, 49900, 1);
INSERT INTO PARAMETRO (NOMBRE, DESCRIPCION, VALOR, AGRUPADOR, ESTADO) VALUES ('Talla', 'Talla de la prenda', 'XL', 'TALLA', 1);
INSERT INTO PRODUCTO (ID_ARTICULO, ID_PARAMETRO, DATA_PRECIO, ESTADO) VALUES (3, 12, 49900, 1);
INSERT INTO ARTICULO (NOMBRE, CODIGO, DESCRIPCION, FIGURE_CLASS, IMG_SRC, IMG_ALT, IMG_CLASS, IMG_ON_CLICK, DATA_CODIGO, DATA_NOMBRE, DATA_DESCRIPCION, FIGCAPTION, ESTADO) VALUES ('Camisa tipo polo gris PFep', 'POL004', 'Camisa gris con diseño clásico PFep', 'wp-block-image size-large', 'https://www.peerkals.com/wp/wp-content/uploads/2025/08/camisas_2-1024x683.png', 'Camisa tipo polo gris PFep', 'wp-image-259 camisa-preview', 'handleClick(this)', 'POL004', 'Camisa tipo polo gris PFep', 'Camisa gris con diseño clásico PFep', 'Camisa tipo polo gris PFep', 1);
INSERT INTO PARAMETRO (NOMBRE, DESCRIPCION, VALOR, AGRUPADOR, ESTADO) VALUES ('Talla', 'Talla de la prenda', 'S', 'TALLA', 1);
INSERT INTO PRODUCTO (ID_ARTICULO, ID_PARAMETRO, DATA_PRECIO, ESTADO) VALUES (4, 13, 49900, 1);
INSERT INTO PARAMETRO (NOMBRE, DESCRIPCION, VALOR, AGRUPADOR, ESTADO) VALUES ('Talla', 'Talla de la prenda', 'M', 'TALLA', 1);
INSERT INTO PRODUCTO (ID_ARTICULO, ID_PARAMETRO, DATA_PRECIO, ESTADO) VALUES (4, 14, 49900, 1);
INSERT INTO PARAMETRO (NOMBRE, DESCRIPCION, VALOR, AGRUPADOR, ESTADO) VALUES ('Talla', 'Talla de la prenda', 'L', 'TALLA', 1);
INSERT INTO PRODUCTO (ID_ARTICULO, ID_PARAMETRO, DATA_PRECIO, ESTADO) VALUES (4, 15, 49900, 1);
INSERT INTO PARAMETRO (NOMBRE, DESCRIPCION, VALOR, AGRUPADOR, ESTADO) VALUES ('Talla', 'Talla de la prenda', 'XL', 'TALLA', 1);
INSERT INTO PRODUCTO (ID_ARTICULO, ID_PARAMETRO, DATA_PRECIO, ESTADO) VALUES (4, 16, 49900, 1);
INSERT INTO ARTICULO (NOMBRE, CODIGO, DESCRIPCION, FIGURE_CLASS, IMG_SRC, IMG_ALT, IMG_CLASS, IMG_ON_CLICK, DATA_CODIGO, DATA_NOMBRE, DATA_DESCRIPCION, FIGCAPTION, ESTADO) VALUES ('Camisa polo mujer PFep', 'POL005', 'Camisa polo entallada para mujer PFep', 'wp-block-image size-large', 'https://www.peerkals.com/wp/wp-content/uploads/2025/08/camisas_3-1024x683.png', 'Camisa polo mujer PFep', 'wp-image-260 camisa-preview', 'handleClick(this)', 'POL005', 'Camisa polo mujer PFep', 'Camisa polo entallada para mujer PFep', 'Camisa polo mujer PFep', 1);
INSERT INTO PARAMETRO (NOMBRE, DESCRIPCION, VALOR, AGRUPADOR, ESTADO) VALUES ('Talla', 'Talla de la prenda', 'S', 'TALLA', 1);
INSERT INTO PRODUCTO (ID_ARTICULO, ID_PARAMETRO, DATA_PRECIO, ESTADO) VALUES (5, 17, 49900, 1);
INSERT INTO PARAMETRO (NOMBRE, DESCRIPCION, VALOR, AGRUPADOR, ESTADO) VALUES ('Talla', 'Talla de la prenda', 'M', 'TALLA', 1);
INSERT INTO PRODUCTO (ID_ARTICULO, ID_PARAMETRO, DATA_PRECIO, ESTADO) VALUES (5, 18, 49900, 1);
INSERT INTO PARAMETRO (NOMBRE, DESCRIPCION, VALOR, AGRUPADOR, ESTADO) VALUES ('Talla', 'Talla de la prenda', 'L', 'TALLA', 1);
INSERT INTO PRODUCTO (ID_ARTICULO, ID_PARAMETRO, DATA_PRECIO, ESTADO) VALUES (5, 19, 49900, 1);
INSERT INTO PARAMETRO (NOMBRE, DESCRIPCION, VALOR, AGRUPADOR, ESTADO) VALUES ('Talla', 'Talla de la prenda', 'XL', 'TALLA', 1);
INSERT INTO PRODUCTO (ID_ARTICULO, ID_PARAMETRO, DATA_PRECIO, ESTADO) VALUES (5, 20, 49900, 1);
INSERT INTO ARTICULO (NOMBRE, CODIGO, DESCRIPCION, FIGURE_CLASS, IMG_SRC, IMG_ALT, IMG_CLASS, IMG_ON_CLICK, DATA_CODIGO, DATA_NOMBRE, DATA_DESCRIPCION, FIGCAPTION, ESTADO) VALUES ('Camisa polo gris mujer PFep', 'POL006', 'Camisa gris para mujer con bordado PFep', 'wp-block-image size-large', 'https://www.peerkals.com/wp/wp-content/uploads/2025/08/camisas_5-683x1024.png', 'Camisa polo gris mujer PFep', 'wp-image-262 camisa-preview', 'handleClick(this)', 'POL006', 'Camisa polo gris mujer PFep', 'Camisa gris para mujer con bordado PFep', 'Camisa polo gris mujer PFep', 1);
INSERT INTO PARAMETRO (NOMBRE, DESCRIPCION, VALOR, AGRUPADOR, ESTADO) VALUES ('Talla', 'Talla de la prenda', 'S', 'TALLA', 1);
INSERT INTO PRODUCTO (ID_ARTICULO, ID_PARAMETRO, DATA_PRECIO, ESTADO) VALUES (6, 21, 49900, 1);
INSERT INTO PARAMETRO (NOMBRE, DESCRIPCION, VALOR, AGRUPADOR, ESTADO) VALUES ('Talla', 'Talla de la prenda', 'M', 'TALLA', 1);
INSERT INTO PRODUCTO (ID_ARTICULO, ID_PARAMETRO, DATA_PRECIO, ESTADO) VALUES (6, 22, 49900, 1);
INSERT INTO PARAMETRO (NOMBRE, DESCRIPCION, VALOR, AGRUPADOR, ESTADO) VALUES ('Talla', 'Talla de la prenda', 'L', 'TALLA', 1);
INSERT INTO PRODUCTO (ID_ARTICULO, ID_PARAMETRO, DATA_PRECIO, ESTADO) VALUES (6, 23, 49900, 1);
INSERT INTO PARAMETRO (NOMBRE, DESCRIPCION, VALOR, AGRUPADOR, ESTADO) VALUES ('Talla', 'Talla de la prenda', 'XL', 'TALLA', 1);
INSERT INTO PRODUCTO (ID_ARTICULO, ID_PARAMETRO, DATA_PRECIO, ESTADO) VALUES (6, 24, 49900, 1);
INSERT INTO ARTICULO (NOMBRE, CODIGO, DESCRIPCION, FIGURE_CLASS, IMG_SRC, IMG_ALT, IMG_CLASS, IMG_ON_CLICK, DATA_CODIGO, DATA_NOMBRE, DATA_DESCRIPCION, FIGCAPTION, ESTADO) VALUES ('Camisa polo manga larga PFep', 'POL007', 'Camisa manga larga con logo PFep', 'wp-block-image size-large', 'https://www.peerkals.com/wp/wp-content/uploads/2025/08/camisas_7-683x1024.png', 'Camisa polo manga larga PFep', 'wp-image-264 camisa-preview', 'handleClick(this)', 'POL007', 'Camisa polo manga larga PFep', 'Camisa manga larga con logo PFep', 'Camisa polo manga larga PFep', 1);
INSERT INTO PARAMETRO (NOMBRE, DESCRIPCION, VALOR, AGRUPADOR, ESTADO) VALUES ('Talla', 'Talla de la prenda', 'S', 'TALLA', 1);
INSERT INTO PRODUCTO (ID_ARTICULO, ID_PARAMETRO, DATA_PRECIO, ESTADO) VALUES (7, 25, 54900, 1);
INSERT INTO PARAMETRO (NOMBRE, DESCRIPCION, VALOR, AGRUPADOR, ESTADO) VALUES ('Talla', 'Talla de la prenda', 'M', 'TALLA', 1);
INSERT INTO PRODUCTO (ID_ARTICULO, ID_PARAMETRO, DATA_PRECIO, ESTADO) VALUES (7, 26, 54900, 1);
INSERT INTO PARAMETRO (NOMBRE, DESCRIPCION, VALOR, AGRUPADOR, ESTADO) VALUES ('Talla', 'Talla de la prenda', 'L', 'TALLA', 1);
INSERT INTO PRODUCTO (ID_ARTICULO, ID_PARAMETRO, DATA_PRECIO, ESTADO) VALUES (7, 27, 54900, 1);
INSERT INTO PARAMETRO (NOMBRE, DESCRIPCION, VALOR, AGRUPADOR, ESTADO) VALUES ('Talla', 'Talla de la prenda', 'XL', 'TALLA', 1);
INSERT INTO PRODUCTO (ID_ARTICULO, ID_PARAMETRO, DATA_PRECIO, ESTADO) VALUES (7, 28, 54900, 1);
INSERT INTO ARTICULO (NOMBRE, CODIGO, DESCRIPCION, FIGURE_CLASS, IMG_SRC, IMG_ALT, IMG_CLASS, IMG_ON_CLICK, DATA_CODIGO, DATA_NOMBRE, DATA_DESCRIPCION, FIGCAPTION, ESTADO) VALUES ('Camisa polo negra PFep', 'POL008', 'Camisa negra con logo bordado PFep', 'wp-block-image size-large', 'https://www.peerkals.com/wp/wp-content/uploads/2025/08/camisas_8-683x1024.png', 'Camisa polo negra PFep', 'wp-image-265 camisa-preview', 'handleClick(this)', 'POL008', 'Camisa polo negra PFep', 'Camisa negra con logo bordado PFep', 'Camisa polo negra PFep', 1);
INSERT INTO PARAMETRO (NOMBRE, DESCRIPCION, VALOR, AGRUPADOR, ESTADO) VALUES ('Talla', 'Talla de la prenda', 'S', 'TALLA', 1);
INSERT INTO PRODUCTO (ID_ARTICULO, ID_PARAMETRO, DATA_PRECIO, ESTADO) VALUES (8, 29, 54900, 1);
INSERT INTO PARAMETRO (NOMBRE, DESCRIPCION, VALOR, AGRUPADOR, ESTADO) VALUES ('Talla', 'Talla de la prenda', 'M', 'TALLA', 1);
INSERT INTO PRODUCTO (ID_ARTICULO, ID_PARAMETRO, DATA_PRECIO, ESTADO) VALUES (8, 30, 54900, 1);
INSERT INTO PARAMETRO (NOMBRE, DESCRIPCION, VALOR, AGRUPADOR, ESTADO) VALUES ('Talla', 'Talla de la prenda', 'L', 'TALLA', 1);
INSERT INTO PRODUCTO (ID_ARTICULO, ID_PARAMETRO, DATA_PRECIO, ESTADO) VALUES (8, 31, 54900, 1);
INSERT INTO PARAMETRO (NOMBRE, DESCRIPCION, VALOR, AGRUPADOR, ESTADO) VALUES ('Talla', 'Talla de la prenda', 'XL', 'TALLA', 1);
INSERT INTO PRODUCTO (ID_ARTICULO, ID_PARAMETRO, DATA_PRECIO, ESTADO) VALUES (8, 32, 54900, 1);