--DROP TABLE if EXISTS donations;
--CREATE TABLE IF NOT EXISTS donations(customer_email VARCHAR(100) PRIMARY KEY,reference VARCHAR(50),customer_name VARCHAR(100), amount_in_cents INT, currency VARCHAR(10), date TIMESTAMP,status VARCHAR(20), clientid INT);
DROP TABLE if EXISTS CLIENTE;
CREATE TABLE IF NOT EXISTS CLIENTE(ID INTEGER PRIMARY KEY AUTOINCREMENT,NOMBRE VARCHAR(250),NUMERODOC VARCHAR(100) UNIQUE,TIPODOC VARCHAR(100),CORREO VARCHAR(250));

DROP TABLE if EXISTS DONACION;
CREATE TABLE IF NOT EXISTS DONACION (ID INTEGER PRIMARY KEY AUTOINCREMENT,AMOUNT_IN_CENTS INT,CURRENCY VARCHAR(100),DATE TIMESTAMP,STATUS VARCHAR(10),CLIENTID INT,FOREIGN KEY (CLIENTID) REFERENCES CLIENTE(ID));